spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db-migrations/changelog.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
